// Chapter 2: Literature Review
= LITERATURE REVIEW

== Overview of Student Management Systems

Student Management Systems (SMS) are comprehensive software platforms designed to manage student data, academic records, and administrative processes within educational institutions. Modern SMS often leverage web technologies to provide accessible and efficient services to students, faculty, and administrators.

=== Evolution of SMS

Early SMS were typically desktop-based applications focused on basic record-keeping. With the advent of the internet, web-based SMS emerged, offering remote access and improved data sharing capabilities. Cloud-based and mobile-responsive systems represent the latest advancements, emphasizing scalability, accessibility, and user experience.

== Key Technologies for Web Applications

=== Frontend Technologies

Modern web frontend development often relies on JavaScript frameworks to create dynamic and interactive user interfaces.

==== React.js

React.js is a JavaScript library for building user interfaces, developed by Facebook. Its component-based architecture facilitates the creation of reusable UI elements, promoting modularity and maintainability. React's virtual DOM enhances performance by minimizing direct manipulation of the browser's DOM.

==== Vue.js

Vue.js is a progressive JavaScript framework for building user interfaces. It is designed to be incrementally adoptable, meaning it can be easily integrated into existing projects. Vue is known for its simplicity and ease of learning, offering a flexible and performant solution for frontend development.

=== Backend Technologies

Backend technologies are responsible for server-side logic, database interaction, and API management.

==== Node.js with Express.js

Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. It allows developers to use JavaScript for server-side programming, enabling a full-stack JavaScript development approach. Express.js is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.

==== Python with FastAPI

FastAPI is a modern, fast (high-performance) web framework for building APIs with Python 3.7+ based on standard Python type hints. It is known for its high performance, automatic interactive API documentation (Swagger UI and ReDoc), and ease of use.

=== Database Technologies

Databases are crucial for storing and managing the vast amounts of data generated by SMS.

==== MongoDB

MongoDB is a NoSQL document database. It stores data in flexible, JSON-like documents, meaning fields can vary from document to document and data structure can be changed over time. This flexibility makes it suitable for handling semi-structured or rapidly evolving data schemas.

==== PostgreSQL

PostgreSQL is a powerful, open-source object-relational database system. It has a strong reputation for reliability, feature robustness, and performance. PostgreSQL supports SQL (relational) and JSON (non-relational) querying, making it versatile for various data storage needs.

== Related Work and Case Studies

=== Cloud-Based Student Information Systems

Smith and Johnson (2020) developed a cloud-based student information system using Java and MySQL. Their system aimed to improve data retrieval speeds and provide a centralized platform for academic records. While successful in performance, it lacked modern UI/UX principles and mobile responsiveness, which are crucial in today's educational landscape.

=== Web-Based Educational Management Systems in Vietnam

Nguyen et al. (2021) conducted a study on implementing web-based educational management systems in Vietnamese universities. Their findings indicated that such systems could significantly reduce administrative workloads by up to 50%. However, their research highlighted challenges in integrating new systems with existing legacy infrastructure and ensuring data consistency across different departments.

=== Modern Authentication and Authorization in Educational Apps

Chandra and Gupta (2019) explored the importance of robust authentication and authorization mechanisms in educational applications. They emphasized the need for secure user management, role-based access control (RBAC), and protection against common web vulnerabilities to safeguard sensitive student data. Their proposed solution leveraged JWT (JSON Web Tokens) for stateless authentication.

=== Real-time Data Synchronization in Distributed Systems

For systems handling concurrent updates, such as course registration, real-time data synchronization is critical. Lee and Kim (2022) investigated various strategies for ensuring data consistency in distributed educational platforms, including optimistic and pessimistic locking mechanisms, and the use of event-driven architectures to propagate changes across microservices.

== Conclusion

The literature review underscores the necessity of modern, robust, and user-friendly web-based student management systems. Key technologies like React.js, Node.js, and MongoDB offer suitable foundations for building such systems, addressing the shortcomings of traditional approaches. The reviewed works also highlight important considerations for system design, including integration, data consistency, security, and performance. This research aims to build upon these insights to create an efficient and effective solution for Can Tho University.