namespace ReSys.Shop.Core.Common.Services.Security.Authorization.Attributes;

/// <summary>
/// Builder for creating authorization configurations in a fluent way.
/// Provides a convenient API for building complex authorization requirements.
/// </summary>
public sealed class AuthorizationBuilder
{
    private readonly List<string> _permissions = [];
    private readonly List<string> _roles = [];
    private readonly List<string> _policies = [];

    /// <summary>
    /// Adds a required permission.
    /// </summary>
    /// <param name="permission">Permission to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePermission(string permission)
    {
        if (!string.IsNullOrWhiteSpace(value: permission))
        {
            _permissions.Add(item: permission);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required permissions.
    /// </summary>
    /// <param name="permissions">Permissions to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePermissions(params string[]? permissions)
    {
        if (permissions != null)
        {
            _permissions.AddRange(collection: permissions.Where(predicate: p => !string.IsNullOrWhiteSpace(value: p)));
        }
        return this;
    }

    /// <summary>
    /// Adds a required role.
    /// </summary>
    /// <param name="role">Role to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequireRole(string role)
    {
        if (!string.IsNullOrWhiteSpace(value: role))
        {
            _roles.Add(item: role);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required roles.
    /// </summary>
    /// <param name="roles">Roles to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequireRoles(params string[]? roles)
    {
        if (roles != null)
        {
            _roles.AddRange(collection: roles.Where(predicate: r => !string.IsNullOrWhiteSpace(value: r)));
        }
        return this;
    }

    /// <summary>
    /// Adds a required policy.
    /// </summary>
    /// <param name="policy">Policy to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePolicy(string policy)
    {
        if (!string.IsNullOrWhiteSpace(value: policy))
        {
            _policies.Add(item: policy);
        }
        return this;
    }

    /// <summary>
    /// Adds multiple required policies.
    /// </summary>
    /// <param name="policies">Policies to require</param>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder RequirePolicies(params string[]? policies)
    {
        if (policies != null)
        {
            _policies.AddRange(collection: policies.Where(predicate: p => !string.IsNullOrWhiteSpace(value: p)));
        }
        return this;
    }

    /// <summary>
    /// Builds the authorization attribute with the configured requirements.
    /// </summary>
    /// <returns>RequestAuthorizeAttribute with the configured requirements</returns>
    /// <exception cref="InvalidOperationException">Thrown when no requirements are configured</exception>
    public RequestAuthorizeAttribute Build()
    {
        if (_permissions.Count == 0 && _roles.Count == 0 && _policies.Count == 0)
        {
            throw new InvalidOperationException(message: "At least one authorization requirement must be configured.");
        }

        string? permissions = _permissions.Count > 0 ? string.Join(separator: ",",
            values: _permissions) : null;
        string? roles = _roles.Count > 0 ? string.Join(separator: ",",
            values: _roles) : null;
        string? policies = _policies.Count > 0 ? string.Join(separator: ",",
            values: _policies) : null;

        return new RequestAuthorizeAttribute(permissions: permissions,
            roles: roles,
            policies: policies);
    }

    /// <summary>
    /// Gets the policy string that would be generated by this builder.
    /// Useful for debugging or caching scenarios.
    /// </summary>
    /// <returns>Policy string</returns>
    public string GetPolicyString()
    {
        return Build().Policy ?? throw new InvalidOperationException(message: "Policy string cannot be null");
    }

    /// <summary>
    /// Creates a new authorization builder.
    /// </summary>
    /// <returns>New AuthorizationBuilder instance</returns>
    public static AuthorizationBuilder Create() => new();

    /// <summary>
    /// Creates a builder pre-configured for admin access.
    /// </summary>
    /// <param name="resource">Optional specific resource for granular admin permissions</param>
    /// <returns>AuthorizationBuilder configured for admin access</returns>
    public static AuthorizationBuilder ForAdmin(string? resource = null)
    {
        AuthorizationBuilder builder = new AuthorizationBuilder()
            .RequireRole(role: "Administrator");

        if (!string.IsNullOrWhiteSpace(value: resource))
        {
            builder.RequirePermission(permission: $"Admin.{resource}.Manage");
        }
        else
        {
            builder.RequirePermission(permission: "Admin.Manage");
        }

        return builder;
    }

    /// <summary>
    /// Creates a builder pre-configured for user management operations.
    /// </summary>
    /// <returns>AuthorizationBuilder configured for user management</returns>
    public static AuthorizationBuilder ForUserManagement() =>
        Create()
            .RequirePermissions(permissions: ["Admin.User.Create", "Admin.User.Update", "Admin.User.Delete"])
            .RequireRole(role: "UserManager");

    /// <summary>
    /// Creates a builder pre-configured for role management operations.
    /// </summary>
    /// <returns>AuthorizationBuilder configured for role management</returns>
    public static AuthorizationBuilder ForRoleManagement() =>
        Create()
            .RequirePermissions(permissions: ["Admin.Role.Create", "Admin.Role.Update", "Admin.Role.Delete"])
            .RequireRole(role: "RoleManager");

    /// <summary>
    /// Resets the builder to its initial state.
    /// </summary>
    /// <returns>This builder for method chaining</returns>
    public AuthorizationBuilder Reset()
    {
        _permissions.Clear();
        _roles.Clear();
        _policies.Clear();
        return this;
    }

    /// <summary>
    /// Returns a summary of the current configuration.
    /// </summary>
    /// <returns>String describing the current configuration</returns>
    public override string ToString()
    {
        List<string> parts = [];

        if (_permissions.Count > 0)
            parts.Add(item: $"Permissions: [{string.Join(separator: ", ", values: _permissions)}]");

        if (_roles.Count > 0)
            parts.Add(item: $"Roles: [{string.Join(separator: ", ", values: _roles)}]");

        if (_policies.Count > 0)
            parts.Add(item: $"Policies: [{string.Join(separator: ", ", values: _policies)}]");

        return parts.Count > 0 ? string.Join(separator: ", ",
            values: parts) : "No requirements configured";
    }
}